version: 2

updates:
  - package-ecosystem: npm
    directory: /
    reviewers: [querkmachine]
    schedule:
      interval: "cron"
      cronjob: "0 4 * */1 6"
    allow:
      - dependency-type: direct
    groups:
      rollup:
        patterns:
          - "rollup"
          - "@rollup/*"

  - package-ecosystem: github-actions
    directory: /
    reviewers: [querkmachine]
    schedule:
      interval: "cron"
      cronjob: "0 4 * */1 6"
